8.01.13

diff --git a/skopiuj_poczte~ b/skopiuj_poczte~
--- a/skopiuj_poczte~
+++ b/skopiuj_poczte~
@@ -3,11 +3,36 @@
 #format wywolania pliku: skopiuj_poczte uzytkownik klient poczty. Przyklad: skopiuj_poczte admin WLM
 #kopiuje poczte z zapisanych sciezek w katalogu poczty
 
-KATALOG_GLOWNY=~/DW/badanie
+KATALOG_GLOWNY=/home/adam/DW/badanie
+
+[[ "$#" != 2  ]] && echo "No enough parameters"  && log "Script started without enough parameters. Error" && exit
 
 function log()
 {
 	echo $1 >> ${KATALOG_GLOWNY}/log.txt 
+}
+
+function konwertujpst()
+{
+	#funckja konwertyje plik pst ktory jest w katalogu outlook na eml do katalogu converted_to_eml
+
+	KATALOG_ZAPISU=$1
+	SCIEZKADOPLIKU=$2
+
+	log "- I start convert Outlook files to eml files"
+
+	#tworzy katalog jesli niema w ktorym beda skonwertowane emaile z pst do eml
+	if [ -d "${KATALOG_ZAPISU}/converted_to_eml" ]; then
+		log "- Folder converted_to_eml exists. OK" 
+	else
+		mkdir "${KATALOG_ZAPISU}/converted_to_eml" && log "- I created folder converted_to_eml correct." || { log "I could NOT create folder converted_to_eml. Error"; exit; }
+	fi
+
+	#wyciaga z calej sciezki tylko ostatni czlon ktory jest plikiem pst
+	PLIK_PST=${SCIEZKADOPLIKU##*/}
+
+	#zapisuje z katalogu Outloog pliki pst do katalogu converted_to_eml skonwertowane pliki
+	readpst  -D -S -e -w -o ${KATALOG_ZAPISU}/converted_to_eml ${KATALOG_ZAPISU}/${PLIK_PST} && log "- I converted Outlook file ${PLIK_PST} to eml file correct" || log "- I coud NOT convert ${PLIK_PST} file"
 }
 
 UZYTKOWNIK=$1
@@ -19,31 +44,35 @@ DATA=`date "+%y-%m-%d %H:%M:%S"`
 
 log "$DATA - Preapering to copy ${KLIENT_POCZTY} files."
 
-if [ ! -d $KATALOG_PRZEZNACZENIA ]; then 
+if [ ! -d ${KATALOG_PRZEZNACZENIA} ]; then 
 	log "-  Error with copy. No ${KATALOG_PRZEZNACZENIA} folder."
-	exit 1; #koniec skryptu
-elif [ ! -e $KATALOG_PRZEZNACZENIA/path_${KLIENT_POCZTY}.txt ]; then
+	exit 
+elif [ ! -e ${KATALOG_PRZEZNACZENIA}/tocopy_${KLIENT_POCZTY}.txt ]; then
 	log "-  Error with copy. No path_${KLIENT_POCZTY}.txt file."
-	exit 1; #koniec skryptu
-elif [ ! -s $KATALOG_PRZEZNACZENIA/path_${KLIENT_POCZTY}.txt ]; then
+	exit 
+elif [ ! -s ${KATALOG_PRZEZNACZENIA}/tocopy_${KLIENT_POCZTY}.txt ]; then
 	log "-  Error with copy. File path_${KLIENT_POCZTY}.txt is empty."
-	exit 1; #koniec skryptu
+	exit  
 else
-	#gdy aoutlook - brak parametru, kopiuje tylko pliki
+	#gdy aoutlook - brak parametru, kopiuje tylko pliki pst
 	#gdy WLM lub Thunderbird nadaje parametr do kopiowania calych katalogow, podkatalogow i plikow
         [ "$KLIENT_POCZTY" == "Outlook" ] && PARAMETR="" || PARAMETR="-R" 
-	#z racji iz potrzebujemy cala strukture kopiujemy wszystkie katalogi z podanej sciezki z pliku
-	[ "$KLIENT_POCZTY" == "WLM" ] && PLIK="path_${KLIENT_POCZTY}.txt" || PLIK="mails_in_${KLIENT_POCZTY}.txt"
 	
-	for SCIEZKA_DO_ORYGINALU in `cat ${KATALOG_PRZEZNACZENIA}/${PLIK}`
+	#wczytuje sciezka po sciezce - pliki do skopiowania i kopiuje pliki jeden po drugim
+	while read SCIEZKA_DO_PLIKU
 	  do
 		#gdy outlook kopiuje tylko wskazany plik gdy inne klienty kopije calle katalogi z plikami
-		cp $PARAMETR "$SCIEZKA_DO_ORYGINALU"  "$KATALOG_PRZEZNACZENIA" &&
-			#jesli sie uda skopiowac
-			log "-  Coped ${KLIENT_POCZTY} files. OK." ||
-				#jesli sie nie uda
-				log "-  Error with copy ${KLIENT_POCZTY} files. Error." 
-	done
+		cp $PARAMETR "$SCIEZKA_DO_PLIKU"  "$KATALOG_PRZEZNACZENIA" 
+		#jesli sie uda skopiowac
+		if [ "$?" == 0 ]; then		
+			log "-  Coped ${SCIEZKA_DO_PLIKU} file to ${KATALOG_PRZEZNACZENIA} - OK."; 
+			#jesli Outlook to od razu konweryjemy pliki pst na eml
+			[[ "$KLIENT_POCZTY" == "Outlook" ]] && konwertujpst "$KATALOG_PRZEZNACZENIA" "$SCIEZKA_DO_PLIKU"; 
+		else
+			log "-  Error with copy ${SCIEZKA_DO_PLIKU} file to ${KATALOG_PRZEZNACZENIA}. Error." 
+		fi
+
+	done < ${KATALOG_PRZEZNACZENIA}/tocopy_${KLIENT_POCZTY}.txt
 fi
 
 
diff --git a/test~ b/test~
--- a/test~
+++ b/test~
@@ -1,11 +1,28 @@
 #!/bin/bash -x
 
+NAZWA_PROGRAMU="Detective Windows 0.3"
+IKONA=~/DW/main/graf/DooFi_detective64.png
 
-ILOSC_ZNALEZIONYCH=`cat ~/DW/badanie/Users/admin/Browsers/Chrome/path_Chrome_arshives.txt | wc -l`
+FILE=welcome.txt
 
-[ "$ILOSC_ZNALEZIONYCH" == 5 ] Z="OK2" 
+zenity --text-info --title="License" --filename=$FILE --checkbox="I read and accept the terms."
 
-echo $Z
+case $? in
+    0)
+        echo "Start installation!"
+	# next step
+	;;
+    1)
+        echo "Stop installation!"
+	;;
+    -1)
+        echo "An unexpected error has occurred."
+	;;
+esac
 
+yad --title="$NAZWA_PROGRAMU" --text="I look for disks and partitions" --timeout=3 --no-buttons
 
+./test2
+#find $HOME -name '*.ps' | yad --progress --pulsate
 
+#yad --title="Desktop entry editor" --text="Simple desktop entry editor" --form --field="Type:CB" --field="Name" --field="Generic name" --field="Comment" --field="Command:FL" --field="Icon" --field="In terminal:CHK" --field="Startup notify:CHK" "Application" "Name" "Generic name" "This is the comment" "/usr/bin/yad" "yad" FALSE TRUE --button="WebUpd8:2" --button="gtk-ok:0" --button="gtk-cancel:1"
